export const levaTheme = {
  colors: {
    elevation1: "#000000",
    elevation2: "#161616",
    elevation3: "#323232",
    accent1: "#ff0000",
    accent2: "#ff0000",
    accent3: "#ff0000",
    highlight1: "#535760",
    highlight2: "#8C92A4",
    highlight3: "#FEFEFE",
    vivid1: "#ffcc00",
  },
  radii: {
    xs: "1px",
    sm: "1px",
    lg: "0px",
  },
  space: {
    sm: "6px",
    md: "10px",
    rowGap: "7px",
    colGap: "7px",
  },
  fontSizes: {
    root: "11px",
  },
  sizes: {
    rootWidth: "100%",
    controlWidth: "160px",
    scrubberWidth: "8px",
    scrubberHeight: "16px",
    rowHeight: "24px",
    folderHeight: "20px",
    checkboxSize: "16px",
    joystickWidth: "100px",
    joystickHeight: "100px",
    colorPickerWidth: "160px",
    colorPickerHeight: "100px",
    monitorHeight: "60px",
    titleBarHeight: "39px",
  },
  borderWidths: {
    root: "0px",
    input: "1px",
    focus: "1px",
    hover: "1px",
    active: "1px",
    folder: "1px",
  },
  fontWeights: {
    label: "normal",
    folder: "normal",
    button: "normal",
  },
};
